### PR TITLE
Added alternate bottom case STL file.

### PR DESCRIPTION
**Pull request by Dark1886**
Added Alternate STL file that has more flat internals that may work better for some printers. Slightly widened batter pocket to fit the battery pack I have. All external geometry and faces that mate with the top piece are untouched.

### CODE REVIEW

**Comment by CoretechR** [comment]
Hi, if you don't mind I would like to move this into a separate folder. Just to avoid confusion with the "official" parts. Maybe we can create a folder (named e.g. Mods) inside CAD?

**Comment by Dark1886** [comment]
Yeah that would be fine, I'll work on changing that.

**Comment by CoretechR** [comment]
@Dark1886 Awesome, thanks!
Just one issue: "OMOTE v25.step" seems to get deleted with this pull request. Could you revert that before I merge it.

**Comment by Dark1886** [comment]
That removal was intentional. It's a mess of a step file honestly.

**Comment by CoretechR** [comment]
Did you mean to just remove "OMOTE-Chunky v1.step" or "OMOTE v25.step"? Because both of them are gone. 😄

**Comment by Dark1886** [comment]
OOOOH. I did not intend to remove the v25 step file.... I will fix that. I very much misunderstood the previous comment.

**Comment by Dark1886** [comment]
NOW this PR is ready.

**Pull request merged**
