### PR TITLE
Add macOS support to the simulator

### PR DESCRIPTION
**Pull request by DDRBoxman**
Users will need to use homebrew (https://brew.sh) to install SDL2 `brew install sdl2`

Screenshot 2024-12-05 at 8 54 13 PM

### CODE REVIEW

**Comment by KlausMu** [comment]
Great, @DDRBoxman , thanks a lot!
Is MQTT also working?

Which steps are exactly needed to install SDL2 on MacOS?
I would like to extend the Wiki at the following places:
https://github.com/CoretechR/OMOTE/wiki/03-Software-simulator-for-fast-creating-and-testing-of-LVGL-GUIs#how-fast-is-it
https://github.com/CoretechR/OMOTE/wiki/03-Software-simulator-for-fast-creating-and-testing-of-LVGL-GUIs#how-to-setup
https://github.com/CoretechR/OMOTE/wiki/03-Software-simulator-for-fast-creating-and-testing-of-LVGL-GUIs#linuxwsl2

**Comment by DDRBoxman** [comment]
MQTT does work!

Screenshot 2024-12-06 at 1 10 09 PM

If the user doesn't have homebrew installed yet they will need to run this to install it:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

( they could also grab it from brew.sh if it makes them feel better)

After that they just need to run `brew install sql2`

And then select the macOS platform in platform.io and click build and then run

**Comment by DDRBoxman** [comment]
(also ignore any weirdness in the second simulator screenshot there, that's from a branch where I've got 90% of the work done to support lvgl 9.2.2 and there are a few weird rending things to clean up)

**Comment by KlausMu** [comment]
> (also ignore any weirdness in the second simulator screenshot there, that's from a branch where I've got 90% of the work done to support lvgl 9.2.2 and there are a few weird rending things to clean up)

There already exists an OMOTE branch for lvgl 9.2 which is fully working and up to date with main:
https://github.com/CoretechR/OMOTE/tree/lvgl_9.1

I did not bring the branch back to main because lvgl 9.x needs significantly more memory, which is critical on the ESP32 if you both need WiFi and BLE. I had a discussion about it in the lvgl forum, with no solution.
https://forum.lvgl.io/t/lvgl-9-higher-memory-usage-and-different-usage-reports-in-lvgl-9-compared-to-8/15308

So in the long run, I think the only way to go is to have a new hardware rev using PSRAM. Please see this discussion https://github.com/CoretechR/OMOTE/discussions/79
I tag @CoretechR so that he reads it :-)

**Comment by DDRBoxman** [comment]
Ah fair enough, I was poking at some SDL stuff to add a window to let you click a virtual keypad and the driver rewrite in 9.2.2 fixed tracking events by window id whereas the old one sends all clicks to all windows. I'll take a look, thanks!

**Comment by KlausMu** [comment]
I merged the PR and brought it to branches `lvgl_9.1` and `multiple-BLE-devices`.
Wiki is also updated.

**Comment by CoretechR** [comment]
Thank your for this great addition, @DDRBoxman !
I just tried it out and it works nicely.

@KlausMu I definitely still have this on my todo list. The holidays might be a good time to design the updated PCB.

**Pull request merged**
